### ISSUE TITLE
Feature Request: Change default toggle status to off

### ISSUE THREAD

**Issue by axemwa** [axemwa/NoStrip#10]

**Comment by axemwa** [comment]
@JohOply can u please test this for bugs, I just added default status as off and included a new placeholder {permission} which works only for the no-permission message atm delete your old config to allow the new placeholder example. I don't have time to test atm as I'm having network issues and have a few things on today please lemme know how you go :)

Also if players don't have nostrip.toggle permission and toggle is OFF it will give them a permission required message but if they have toggle OFF and they do have the nostrip.toggle permission then the permission message won't spam and they'll just have to toggle it on when they want to use it. Hope it all works ok I'm getting better at this. Make sure to remove any permissions that are already set before testing and to ensure to delete your old config

https://www.dropbox.com/s/ujhxhgcjm2sfu3z/NoStrip-Test.jar?dl=1

**Comment by axemwa** [comment]
Added in latest version
https://www.spigotmc.org/resources/nostrip.61574/
I've also added the option to choose the default toggle option for players in config

**Comment by JohOply** [comment]
Yeah it's work.

I found a bug, reported here https://github.com/axemwa/NoStrip/issues/12
