### ISSUE TITLE
Feature request: Be able to choose default status for toggle in config

### ISSUE THREAD

**Issue by JohOply** [axemwa/NoStrip#4]
Hi!

Could you add an option to choose default status in config?
I want new player have status "false" and they are able to enable it if they want

Thanks

**Comment by axemwa** [comment]
Will look into it, I was already intending to add this in future as well as it remembering the players choices. I'll see if I can get it sorted within the week

**Comment by JohOply** [comment]
It will be nice!

Also you could add an option to reset status/players choices on each logout, which apply default setting choosen in config

**Comment by axemwa** [comment]
Isn't that what u meant in the first message?

**Comment by JohOply** [comment]
Not exaclty I think
To sum up ideas:
- add an option to define default status in config (disable in my case)
- because you will add a setting to remember status players choices, you could add another option to forget the choice on logout (like it works today) and apply default status on every login (in my case I want force player to enable on every login, to prevent accidents)

**Comment by axemwa** [comment]
Yeah that's pretty much what u already said, I understood what u wanted from the 1st message. All good just making sure I understand that's all and I will add/fix this

**Comment by axemwa** [comment]
Oh nvm soz my bad, I think I understand what you mean now, so just to clarify,

1. You want it to have an option for default toggle in config as to what the default should be

config eg: 

Set default toggle to ON or OFF
default-toggle : ON

2. You want an option as to whether or not the plugin will remember what the players toggle was the last time they used it?

config eg:

Remember players toggle option? (if disabled relies on default-toggle option)
remember-toggle: enabled

**Comment by JohOply** [comment]
Yeah that's correct

With that, if i set "default-toggle: off" and "remember-toggle: disabled", on each login the toggle will be disabled". That's my goal :)

**Comment by axemwa** [comment]
ok soz taking a while to get around to it I'm still a noob dev lol gotta re-train my brain as I haven't worked on it in a while

**Comment by axemwa** [comment]
thanx for your patience

**Comment by JohOply** [comment]
Hi there
Some news about next update of the plugin? :)

**Comment by axemwa** [comment]
Sorry about this I currently no longer have time to work on the project, I am intending to ask one of my friends to take over the project who is a lot more skilled in programming

**Comment by JohOply** [comment]
That's a pitty :/
I hope it will be continued :)
Good luck in your stuff

**Comment by JohOply** [comment]
@axemwa You said default status is "off" in https://github.com/axemwa/NoStrip/issues/9
But it's not, default status is on currently. Waiting for this feature to choose default status, could you set off by default?

**Comment by axemwa** [comment]
Sorry yes I meant default toggle status is ON currently I just meant players won't be able to strip by default unless they have the axe permissions and got it mixed around. Sure I will set toggle status to off by default I will have to add in an extra message informing the player that stripping is toggled off though as currently there is no deny message for when toggle is off. 

Toggle was originally intended for players so that they can turn the toggle off so they don't accidentally strip the tree when right clicking near it but I can see why u want it off by default as it will allow for even more control for server owners. I will try to add this soon thank you for your time, patience and suggestion(s).

**Comment by axemwa** [comment]
Being able to choose default status in config will come later down the track though as I will only be doing 1-2 small updates at a time until I get more experienced at coding so I can add in more advanced features. Thankyou for being patient I'm glad you're enjoying my very first plugin take care :)

**Comment by axemwa** [comment]
Added in latest version
https://www.spigotmc.org/resources/nostrip.61574/
Remembering players choice will come at a later date when I get more experienced.
Enjoy!
