### ISSUE TITLE
Bug: Reload command not working

### ISSUE THREAD

**Issue by JohOply** [axemwa/NoStrip#5]
Hi

/ns reload seems do not work (config is not modified)
There is no error in console
I use Spigot b2090 (1.13.2) and NoStrip 1.7

**Comment by axemwa** [comment]
Hmm that's strange what changes are u trying the make specifically? I'll look into this

**Comment by JohOply** [comment]
I tried to change messages. I get the message "Config reloaded" but it is not true yet :/
However, a restart apply all my changes

**Comment by axemwa** [comment]
And this does this for all messages?

**Comment by JohOply** [comment]
Yes it is

**Comment by axemwa** [comment]
Fixed as of Version 2.0
https://www.spigotmc.org/resources/nostrip.61574/

**Comment by JohOply** [comment]
It's work, perfect :)
