### ISSUE TITLE
Need Help with Permissions

### ISSUE THREAD

**Issue by InsaneCallum** [axemwa/NoStrip#9]
Yes, im aware im probably being dumb, im new to this permission stuff. Am i doing this correct?

I want to disable stripping for everyone except if they are using a wooden axe. However this isnt working. Could you please inform me what i am doing wrong? Thanks

![image](https://user-images.githubusercontent.com/50807125/62904203-4a706980-bd5d-11e9-87b7-35975c41800b.png)

**Comment by axemwa** [comment]
By default no one should be able to strip logs unless they have `"nostrip.axe.<axetype>"` for permission to use a specific axe.
eg: "nostrip.axe.diamond" will allow players to strip logs/wood with a diamond axe
To allow all axes use "nostrip.axe.*" 

To toggle log stripping on or off (off by default) use "/ns toggle" which requires the permission "nostrip.toggle".
I've never used PEX so I don't know how that gets configured but I have tested this with luckperms and it works fine.
Make sure you are not stripping WOOD as WOOD is different to LOGS and hasn't been implemented yet. Also make sure none of your players are op cause being op gives all permissions.

One thing to try if all else fails in PEX is to negate all permissions except for the axe you want to use, if you end up getting this working please close the issue and let me know how you went.

Ps: I'll be releasing an update soon which denies stripping from the offhand as it only denies the mainhand atm also the update will prevent stripping of all WOOD types as well as LOG types

**Comment by axemwa** [comment]
New version has been released
https://www.spigotmc.org/resources/nostrip.61574/

**Comment by JohOply** [comment]
I recommand LuckPerms too, plugin is actively maintained and dev could help you when you have questions :) https://www.spigotmc.org/resources/luckperms-an-advanced-permissions-plugin.28140/

**Comment by InsaneCallum** [comment]
Thankyou soo much! Working fine with PermissionsEx, originally got it as normal permissions.yml i just couldnt get working.

**Comment by axemwa** [comment]
> 
> 
> @axemwa You said default status is "off" in #9
> But it's not, default status is on currently. Waiting for this feature to choose default status, could you set off by default?

Sorry as JohOply said in the other issue tracker the toggle is actually ON by default not OFF my bad got my words mixed up and being able to choose the default toggle via config will come later down the track, but I will be changing the default toggle from my end soon will keep ya posted
